goodsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('swank.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

swank/urls.py
from django.urls import path
from .views import index,newfunc, createfunc, createuser

urlpatterns = [
    path('index/', index, name="index"),
    path('new/', newfunc, name="newfunc"),
    path('create/', createfunc, name="createfunc"),
    path('createuser/', createuser, name="createuser"),
]

swank/models.py
from django.db import models

# Create your models here.
class UserModel(models.Model):
    name = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    favorite = models.CharField(max_length=255, null=True, blank=True)

class SiteModel(models.Model):
    name = models.CharField(max_length=100)
    SITE_CHOICES = [
        ('blog', 'ブログサイト'),
        ('promo', 'プロモーションサイト'),
        ('portfo', 'ポートフォリオサイト'),
        ('ecsite', 'ECサイト'),
        ('corp', 'コーポレートサイト'),
        ('recru', 'リクルートサイト'),
        ('landing', 'ランディングページ'),
    ]
    sitekind = models.CharField(max_length=20, choices=SITE_CHOICES, default='blog')
    siteurl = models.URLField(max_length=100)
    gooduser = models.CharField(max_length=255, null=True, blank=True)
    postuser = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    images = models.ImageField(upload_to='')

class Comment(models.Model):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    site = models.ForeignKey(SiteModel, on_delete=models.CASCADE)
    comment = models.TextField()

swank/views.py
from django.shortcuts import render, redirect
from .scshot import scshotfunc
import os
from .models import UserModel, SiteModel, Comment

# Create your views here.
def index(request):
    sites = SiteModel.objects.all().order_by('-id')
    if request.method == 'POST':
        sitekind = request.POST['sitekind']
        if sitekind == "allkind":
            sites = SiteModel.objects.all().order_by('-id')
        else:
            sites = sites.filter(sitekind=sitekind)
    return render(request, 'index.html', {
        'sites': sites,
    })

def newfunc(request):
    # choicetoselect = SiteModel.SITE_CHOICES
    return render(request, 'new.html')

def createfunc(request):
    sitename = request.POST['sitename']
    sitekind = request.POST['sitekind']
    siteurl = request.POST['siteurl']
    username = request.POST['username']
    password = request.POST['password']
    userinfo = UserModel.objects.filter(name=username)
    userinfo = userinfo.filter(password=password)
    print(userinfo)
    siteCheck = SiteModel.objects.filter(siteurl=siteurl)
    if sitename == "" or sitekind == "" or siteurl == "" or username == "" or password == "":
        sites = SiteModel.objects.all().order_by('-id')
        message = "全ての項目を入力してください"
        return render(request, 'index.html', {
            'sites': sites,
            'message': message,
            })

    if userinfo.first() is not None:
        if siteCheck.first() is None:
            # 全画面スクリーンショット機能
            scshotfunc(siteurl)
            # サイト名.pngになるようにする
            oldname = 'noname.png'
            newname = str(userinfo[0]) + sitename + '.png'
            os.rename('media/' + oldname, 'media/' + newname)
            siteinfo = SiteModel(name=sitename, sitekind=sitekind, siteurl=siteurl, gooduser='', postuser=userinfo[0], images=newname)
            siteinfo.save()
            return redirect('index')
        else:
            message = 'そのサイトはすでに登録されています。'
            sites = SiteModel.objects.all().order_by('-id')
            return render(request, 'index.html', {
            'sites': sites,
            'message': message,
            })
        #     return render(request, 'createuser.html',{
        #     'sitename': sitename,
        #     'sitekind': sitekind,
        #     'siteurl': siteurl,
        #     'message': message,
        # })
    else:
        return render(request, 'createuser.html',{
            'sitename': sitename,
            'sitekind': sitekind,
            'siteurl': siteurl,
        })

def createuser(request):
    sitename = request.POST['sitename']
    sitekind = request.POST['sitekind']
    siteurl = request.POST['siteurl']
    username = request.POST['username']
    password = request.POST['password']
    userinfo = UserModel.objects.filter(name=username)
    userinfo = userinfo.filter(password=password)
    if username == "" or password == "":
        message = 'ユーザー名、パスワードに空欄があります。'
        sites = SiteModel.objects.all().order_by('-id')
        return render(request, 'index.html', {
        'sites': sites,
        'message': message,
        })
    if userinfo.first() is None:
        setuserinfo = UserModel(name=username, password=password, favorite="")
        setuserinfo.save()
        userinfo = UserModel.objects.filter(name=username)
        userinfo = userinfo.filter(password=password)
        # 全画面スクリーンショット機能
        scshotfunc(siteurl)
        # サイト名.pngになるようにする
        oldname = 'noname.png'
        newname = sitename + '.png'
        os.rename('media/' + oldname, 'media/' + newname)
        siteinfo = SiteModel(name=sitename, sitekind=sitekind, siteurl=siteurl, gooduser='', postuser=userinfo[0], images=newname)
        siteinfo.save()
        return redirect('index')
    return redirect('index')

    

templates/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% block customcss %}
    {% endblock customcss %}
    <title>みんなが選ぶおしゃれサイト</title>
  </head>
  <body>
    {% block header %}
    {% endblock %}
    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/createuser.html
{% extends 'base.html' %}
{% load static %}

{% block customcss %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
{% endblock customcss %}
{% block content %}
<form action="{% url 'createuser' %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="sitename" value="{{sitename}}">
    <input type="hidden" name="sitekind" value="{{sitekind}}">
    <input type="hidden" name="siteurl" value="{{siteurl}}">
    <p>ユーザー名：<input type="text" name="username" size="30" maxlength="40"></p>
    <p>パスワード：<input type="text" name="password" size="30" maxlength="40"></p>
    <input type="submit" value="投稿する">
</form>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block customcss %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<meta name=”viewport” content=”width=device-width, initial-scale=1”>
{% endblock customcss %}

{% block content %}

<div class="container serch">
    <form action="{% url 'index' %}" method="POST" id="serchform">
        {% csrf_token %}
        <p>サイト種類：
            <select name="sitekind">
            <option value="allkind">全種類</option>
            <option value="blog">ブログサイト</option>
            <option value="promo">プロモーションサイト</option>
            <option value="portfo">ポートフォリオサイト</option>
            <option value="ecsite">ECサイト</option>
            <option value="corp">コーポレートサイト</option>
            <option value="recru">リクルートサイト</option>
            <option value="landing">ランディングページ</option>
            </select>
        </p>
        <input class="btn btn-outline-primary serchbutton" type="submit" value="検索">
    </form>
</div>


<div id="post">
    <a href="{%url 'newfunc'%}">
        <button type="button" class="btn btn-outline-primary">おしゃれサイトを投稿</button>
    </a>
    {{message}}
</div>
<div class="sites">
{% for site in sites %}
<div class="siteinfo">
    <ul>
        <div class="sitedetails">
        <li>
            <div class="site-detail">
                <div class="left">サイト名</div>
                <div class="right">{{site.name}}</div>
            </div>
        </li>
        <li>
            <div class="site-detail">
                <div class="left">種類</div>
                <div class="right">{{site.get_sitekind_display}}</div>
            </div>
        </li>
        <li>
            <div class="site-detail">
                <div class="left">URL</div>
                <div class="right"><a href="{{ site.siteurl }}">サイトへ移動</a></div>
            </div>
        </li>
        <li>
            <div class="site-detail">
                <div class="left">投稿者</div>
                <div class="right">{{site.postuser.name}}さん</div>
            </div>
        </li>
        </div>
        <li>
            <div class="img_cover"><img src="{{site.images.url}}" width=300></div>
        </li>
    </ul>
</div>
    {% endfor %}
</div>
{% endblock %}

templates/new.html
{% extends 'base.html' %}
{% load static %}

{% block customcss %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
{% endblock customcss %}
{% block content %}
<h4>おしゃれサイト投稿画面</h4>
<div class="container create-container">
<form action="{% url 'createfunc' %}" method="POST">
    {% csrf_token %}
    <p>サイト名：<input type="text" name="sitename" size="30" maxlength="40"></p>
    <p>サイト種類：
        <select name="sitekind" id="kind-select">
        <option value="blog">ブログサイト</option>
        <option value="promo">プロモーションサイト</option>
        <option value="portfo">ポートフォリオサイト</option>
        <option value="ecsite">ECサイト</option>
        <option value="corp">コーポレートサイト</option>
        <option value="recru">リクルートサイト</option>
        <option value="landing">ランディングページ</option>
        </select>
    </p>
    <p>サイトURL：<input type="url" name="siteurl" size="30" maxlength="40"></p>
    <p>ユーザー名：<input type="text" name="username" size="30" maxlength="40"></p>
    <p>パスワード：<input type="password" name="password" size="30" maxlength="40"></p>
    <input type="submit" value="投稿する" class="btn btn-outline-primary">
</form>
</div>
{% endblock content %}